--CONDITIONAL CONTROL STATEMENTS(KOÞULLU AKIÞ KONTROLLERI) IF - CASE

--IF

--        DECLARE
--          DOGUM_TARIHI DATE := TO_DATE('06/04/1965','DD/MM/YYYY');
--          YASI NUMBER(2,0);
--        BEGIN
--            YASI:=(SYSDATE-DOGUM_TARIHI)/365;
--            IF YASI < 15 THEN 
--                DBMS_OUTPUT.PUT_LINE('BEN BIR COCUGUM! YAÞIM: '|| YASI);
--            ELSIF YASI <40 THEN
--                DBMS_OUTPUT.PUT_LINE('BEN BIR GENCÝM! YAÞIM: '|| YASI); 
--            ELSE 
--                DBMS_OUTPUT.PUT_LINE('BEN BIR YETÝÞKÝNÝM! YAÞIM: '|| YASI);
--            END IF;
--        END;

-- CASE (SIMPLECASE && SEARCHCASE)
--SEARCHED CASE
--DECLARE
--  DOGUM_TARIHI DATE := TO_DATE('06/04/2015','DD/MM/YYYY');
--  YASI NUMBER(2,0);
--  CIKTI VARCHAR2(2000);
--BEGIN
--    YASI:=(SYSDATE-DOGUM_TARIHI)/365;
--    CASE
--        WHEN YASI<15 THEN CIKTI:='BEN BIR COCUGUM! YAÞIM: '|| YASI;
--        WHEN YASI<20 THEN CIKTI:='BEN 10 LU YAÞLARDAYIM! VE  YAÞIM: '|| YASI;
--            CASE
--                WHEN YASI>18 THEN CIKTI:='BEN 19 YASINDAYIM! VE YAÞIM: '|| YASI;
--            END CASE;
--        WHEN YASI<30 THEN CIKTI:='BEN 20 LÝ YAÞLARDAYIM! VE  YAÞIM: '|| YASI;
--        WHEN YASI<40 THEN CIKTI:='BEN 30 LU YAÞLARDAYIM! VE  YAÞIM: '|| YASI;
--        WHEN YASI<50 THEN CIKTI:='BEN 40 LI YAÞLARDAYIM! VE  YAÞIM: '|| YASI;
--        WHEN YASI<60 THEN CIKTI:='BEN 50 LÝ YAÞLARDAYIM! VE  YAÞIM: '|| YASI;
--        ELSE CIKTI:='BEN BIR COCUK DEÐÝLÝM! YAÞIM: '|| YASI;
--    END CASE;
--    DBMS_OUTPUT.PUT_LINE(CIKTI);
--END;
--SIMPLE CASE
DECLARE
  SAYI NUMBER := &SAYIEKRAN; --DIÞARDAN SAYI ALMAK ÝÇÝN '&'
  CIKTI VARCHAR2(2000);
BEGIN
  CASE MOD(SAYI,2)
    WHEN 1 THEN CIKTI:='TEK SAYI ' || SAYI;
    ELSE        CIKTI:='ÇÝFT SAYI '|| SAYI;
  END CASE;
  DBMS_OUTPUT.PUT_LINE(CIKTI);
END;
      
         

