--DESC REGIONS

--SELECT * FROM REGIONS

--CREATE SEQUENCE TEST_SEQ START WITH 5 INCREMENT BY 1;

DECLARE
    SEQ_NUM NUMBER := TEST_SEQ.NEXTVAL;
BEGIN
    INSERT INTO REGIONS (REGION_ID,REGION_NAME) VALUES (SEQ_NUM,'AVUSTRALYA');
    SEQ_NUM :=TEST_SEQ.CURRVAL;
    UPDATE REGIONS SET REGION_NAME = 'ANTARTÝKA' WHERE REGION_ID=SEQ_NUM;
END;